{{- if and .Values.calendar.storage.pvc.enabled (eq .Values.calendar.storage.pvc.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "calendar.fullname" . }}-data
spec:
  accessModes:
{{- range .Values.calendar.storage.pvc.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.calendar.storage.pvc.size }}
  {{- if .Values.calendar.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.calendar.storage.pvc.storageClassName }}
  {{- end }}
{{- end }}
